const keywords = {
    "meta": {
        "model": "Neuro-Archetypes v4.0 (IRH Code System)",
        "version": "4.0",
        "total_keywords": 64,
        "axis_logic": {
            "x": "Drive ( I:Individual/Competition > 0 | O:Others/Connection < 0 )",
            "y": "Entropy ( H:Hot/Chaos > 0 | C:Cold/Order < 0 )",
            "z": "Topology ( R:Real/Sensory > 0 | V:Virtual/Prediction < 0 )"
        }
    },
    "keywords": [
        { "id": 1, "keyword_zh": "征服", "keyword_en": "Conquer", "archetype": "Hunter", "vector": { "x": 0.95, "y": 0.85, "z": 0.90 } },
        { "id": 2, "keyword_zh": "衝刺", "keyword_en": "Sprint", "archetype": "Hunter", "vector": { "x": 0.80, "y": 0.90, "z": 0.75 } },
        { "id": 3, "keyword_zh": "奪取", "keyword_en": "Seize", "archetype": "Hunter", "vector": { "x": 0.88, "y": 0.70, "z": 0.85 } },
        { "id": 4, "keyword_zh": "戰鬥", "keyword_en": "Fight", "archetype": "Hunter", "vector": { "x": 0.92, "y": 0.88, "z": 0.82 } },
        { "id": 5, "keyword_zh": "冒險", "keyword_en": "Risk", "archetype": "Hunter", "vector": { "x": 0.75, "y": 0.95, "z": 0.60 } },
        { "id": 6, "keyword_zh": "狩獵", "keyword_en": "Hunt", "archetype": "Hunter", "vector": { "x": 0.85, "y": 0.65, "z": 0.95 } },
        { "id": 7, "keyword_zh": "突破", "keyword_en": "Break", "archetype": "Hunter", "vector": { "x": 0.70, "y": 0.80, "z": 0.70 } },
        { "id": 8, "keyword_zh": "競爭", "keyword_en": "Vying", "archetype": "Hunter", "vector": { "x": 0.90, "y": 0.60, "z": 0.65 } },
        { "id": 9, "keyword_zh": "贏家", "keyword_en": "Winner", "archetype": "Hunter", "vector": { "x": 0.98, "y": 0.50, "z": 0.88 } },
        { "id": 10, "keyword_zh": "冠軍", "keyword_en": "Champ", "archetype": "Hunter", "vector": { "x": 0.92, "y": 0.45, "z": 0.92 } },
        { "id": 11, "keyword_zh": "豪賭", "keyword_en": "Bet", "archetype": "Hunter", "vector": { "x": 0.65, "y": 0.98, "z": 0.55 } },
        { "id": 12, "keyword_zh": "猛攻", "keyword_en": "Storm", "archetype": "Hunter", "vector": { "x": 0.85, "y": 0.92, "z": 0.80 } },
        { "id": 13, "keyword_zh": "斬獲", "keyword_en": "Gain", "archetype": "Hunter", "vector": { "x": 0.82, "y": 0.55, "z": 0.90 } },
        { "id": 14, "keyword_zh": "支配", "keyword_en": "Rule", "archetype": "Hunter", "vector": { "x": 0.96, "y": 0.40, "z": 0.75 } },
        { "id": 15, "keyword_zh": "擴張", "keyword_en": "Grow", "archetype": "Hunter", "vector": { "x": 0.78, "y": 0.75, "z": 0.68 } },
        { "id": 16, "keyword_zh": "掠奪", "keyword_en": "Loot", "archetype": "Hunter", "vector": { "x": 0.89, "y": 0.82, "z": 0.89 } },
        { "id": 17, "keyword_zh": "創新", "keyword_en": "New", "archetype": "Pioneer", "vector": { "x": 0.80, "y": 0.85, "z": -0.70 } },
        { "id": 18, "keyword_zh": "變革", "keyword_en": "Reform", "archetype": "Pioneer", "vector": { "x": 0.85, "y": 0.90, "z": -0.60 } },
        { "id": 19, "keyword_zh": "顛覆", "keyword_en": "Shift", "archetype": "Pioneer", "vector": { "x": 0.90, "y": 0.95, "z": -0.50 } },
        { "id": 20, "keyword_zh": "創業", "keyword_en": "Start", "archetype": "Pioneer", "vector": { "x": 0.88, "y": 0.80, "z": -0.40 } },
        { "id": 21, "keyword_zh": "願景", "keyword_en": "Vision", "archetype": "Pioneer", "vector": { "x": 0.70, "y": 0.60, "z": -0.95 } },
        { "id": 22, "keyword_zh": "狂熱", "keyword_en": "Mania", "archetype": "Pioneer", "vector": { "x": 0.65, "y": 0.98, "z": -0.30 } },
        { "id": 23, "keyword_zh": "靈感", "keyword_en": "Idea", "archetype": "Pioneer", "vector": { "x": 0.50, "y": 0.75, "z": -0.85 } },
        { "id": 24, "keyword_zh": "獨創", "keyword_en": "Unique", "archetype": "Pioneer", "vector": { "x": 0.75, "y": 0.70, "z": -0.65 } },
        { "id": 25, "keyword_zh": "異類", "keyword_en": "Alien", "archetype": "Pioneer", "vector": { "x": 0.60, "y": 0.88, "z": -0.55 } },
        { "id": 26, "keyword_zh": "奇蹟", "keyword_en": "Magic", "archetype": "Pioneer", "vector": { "x": 0.55, "y": 0.82, "z": -0.90 } },
        { "id": 27, "keyword_zh": "夢想", "keyword_en": "Dream", "archetype": "Pioneer", "vector": { "x": 0.45, "y": 0.65, "z": -0.98 } },
        { "id": 28, "keyword_zh": "改造", "keyword_en": "Remake", "archetype": "Pioneer", "vector": { "x": 0.82, "y": 0.78, "z": -0.45 } },
        { "id": 29, "keyword_zh": "演化", "keyword_en": "Evolve", "archetype": "Pioneer", "vector": { "x": 0.68, "y": 0.72, "z": -0.80 } },
        { "id": 30, "keyword_zh": "實驗", "keyword_en": "Test", "archetype": "Pioneer", "vector": { "x": 0.72, "y": 0.68, "z": -0.35 } },
        { "id": 31, "keyword_zh": "發明", "keyword_en": "Invent", "archetype": "Pioneer", "vector": { "x": 0.78, "y": 0.55, "z": -0.75 } },
        { "id": 32, "keyword_zh": "天才", "keyword_en": "Genius", "archetype": "Pioneer", "vector": { "x": 0.95, "y": 0.92, "z": -0.88 } },
        { "id": 33, "keyword_zh": "表演", "keyword_en": "Act", "archetype": "Gatherer", "vector": { "x": -0.85, "y": 0.90, "z": 0.80 } },
        { "id": 34, "keyword_zh": "魅力", "keyword_en": "Charm", "archetype": "Gatherer", "vector": { "x": -0.90, "y": 0.70, "z": 0.75 } },
        { "id": 35, "keyword_zh": "狂歡", "keyword_en": "Revel", "archetype": "Gatherer", "vector": { "x": -0.75, "y": 0.95, "z": 0.85 } },
        { "id": 36, "keyword_zh": "激情", "keyword_en": "Fire", "archetype": "Gatherer", "vector": { "x": -0.80, "y": 0.88, "z": 0.70 } },
        { "id": 37, "keyword_zh": "娛樂", "keyword_en": "Fun", "archetype": "Gatherer", "vector": { "x": -0.70, "y": 0.80, "z": 0.65 } },
        { "id": 38, "keyword_zh": "閃耀", "keyword_en": "Shine", "archetype": "Gatherer", "vector": { "x": -0.95, "y": 0.85, "z": 0.60 } },
        { "id": 39, "keyword_zh": "誘惑", "keyword_en": "Lure", "archetype": "Gatherer", "vector": { "x": -0.88, "y": 0.75, "z": 0.55 } },
        { "id": 40, "keyword_zh": "喧鬧", "keyword_en": "Loud", "archetype": "Gatherer", "vector": { "x": -0.65, "y": 0.92, "z": 0.90 } },
        { "id": 41, "keyword_zh": "活潑", "keyword_en": "Vivid", "archetype": "Gatherer", "vector": { "x": -0.60, "y": 0.78, "z": 0.82 } },
        { "id": 42, "keyword_zh": "潮流", "keyword_en": "Trend", "archetype": "Gatherer", "vector": { "x": -0.78, "y": 0.82, "z": 0.50 } },
        { "id": 43, "keyword_zh": "互動", "keyword_en": "React", "archetype": "Gatherer", "vector": { "x": -0.92, "y": 0.65, "z": 0.88 } },
        { "id": 44, "keyword_zh": "體驗", "keyword_en": "Feel", "archetype": "Gatherer", "vector": { "x": -0.55, "y": 0.60, "z": 0.95 } },
        { "id": 45, "keyword_zh": "驚喜", "keyword_en": "Wow", "archetype": "Gatherer", "vector": { "x": -0.68, "y": 0.98, "z": 0.45 } },
        { "id": 46, "keyword_zh": "派對", "keyword_en": "Party", "archetype": "Gatherer", "vector": { "x": -0.82, "y": 0.86, "z": 0.92 } },
        { "id": 47, "keyword_zh": "玩樂", "keyword_en": "Play", "archetype": "Gatherer", "vector": { "x": -0.50, "y": 0.72, "z": 0.78 } },
        { "id": 48, "keyword_zh": "享受", "keyword_en": "Joy", "archetype": "Gatherer", "vector": { "x": -0.45, "y": 0.55, "z": 0.98 } },
        { "id": 49, "keyword_zh": "靈性", "keyword_en": "Spirit", "archetype": "Shaman", "vector": { "x": -0.80, "y": 0.85, "z": -0.90 } },
        { "id": 50, "keyword_zh": "慈悲", "keyword_en": "Mercy", "archetype": "Shaman", "vector": { "x": -0.95, "y": 0.60, "z": -0.50 } },
        { "id": 51, "keyword_zh": "理想", "keyword_en": "Ideal", "archetype": "Shaman", "vector": { "x": -0.75, "y": 0.90, "z": -0.85 } },
        { "id": 52, "keyword_zh": "救贖", "keyword_en": "Save", "archetype": "Shaman", "vector": { "x": -0.85, "y": 0.75, "z": -0.65 } },
        { "id": 53, "keyword_zh": "連結", "keyword_en": "Link", "archetype": "Shaman", "vector": { "x": -0.98, "y": 0.55, "z": -0.70 } },
        { "id": 54, "keyword_zh": "啟發", "keyword_en": "Muse", "archetype": "Shaman", "vector": { "x": -0.70, "y": 0.80, "z": -0.75 } },
        { "id": 55, "keyword_zh": "感通", "keyword_en": "Sense", "archetype": "Shaman", "vector": { "x": -0.90, "y": 0.65, "z": -0.80 } },
        { "id": 56, "keyword_zh": "自由", "keyword_en": "Free", "archetype": "Shaman", "vector": { "x": -0.65, "y": 0.95, "z": -0.40 } },
        { "id": 57, "keyword_zh": "藝術", "keyword_en": "Art", "archetype": "Shaman", "vector": { "x": -0.60, "y": 0.88, "z": -0.95 } },
        { "id": 58, "keyword_zh": "奉獻", "keyword_en": "Give", "archetype": "Shaman", "vector": { "x": -0.92, "y": 0.50, "z": -0.45 } },
        { "id": 59, "keyword_zh": "犧牲", "keyword_en": "Loss", "archetype": "Shaman", "vector": { "x": -0.88, "y": 0.70, "z": -0.35 } },
        { "id": 60, "keyword_zh": "信仰", "keyword_en": "Faith", "archetype": "Shaman", "vector": { "x": -0.82, "y": 0.68, "z": -0.92 } },
        { "id": 61, "keyword_zh": "奇幻", "keyword_en": "Magic", "archetype": "Shaman", "vector": { "x": -0.55, "y": 0.92, "z": -0.98 } },
        { "id": 62, "keyword_zh": "覺醒", "keyword_en": "Wake", "archetype": "Shaman", "vector": { "x": -0.72, "y": 0.82, "z": -0.60 } },
        { "id": 63, "keyword_zh": "融合", "keyword_en": "Merge", "archetype": "Shaman", "vector": { "x": -0.96, "y": 0.98, "z": -0.30 } },
        { "id": 64, "keyword_zh": "傳道", "keyword_en": "Preach", "archetype": "Shaman", "vector": { "x": -0.78, "y": 0.58, "z": -0.55 } },
        { "id": 65, "keyword_zh": "執行", "keyword_en": "Do", "archetype": "Toolmaker", "vector": { "x": 0.70, "y": -0.80, "z": 0.90 } },
        { "id": 66, "keyword_zh": "精確", "keyword_en": "Exact", "archetype": "Toolmaker", "vector": { "x": 0.60, "y": -0.95, "z": 0.85 } },
        { "id": 67, "keyword_zh": "績效", "keyword_en": "KPI", "archetype": "Toolmaker", "vector": { "x": 0.85, "y": -0.75, "z": 0.80 } },
        { "id": 68, "keyword_zh": "效率", "keyword_en": "Fast", "archetype": "Toolmaker", "vector": { "x": 0.80, "y": -0.85, "z": 0.75 } },
        { "id": 69, "keyword_zh": "實務", "keyword_en": "Real", "archetype": "Toolmaker", "vector": { "x": 0.55, "y": -0.60, "z": 0.95 } },
        { "id": 70, "keyword_zh": "鍛鍊", "keyword_en": "Train", "archetype": "Toolmaker", "vector": { "x": 0.75, "y": -0.50, "z": 0.88 } },
        { "id": 71, "keyword_zh": "建設", "keyword_en": "Build", "archetype": "Toolmaker", "vector": { "x": 0.68, "y": -0.45, "z": 0.92 } },
        { "id": 72, "keyword_zh": "操控", "keyword_en": "Drive", "archetype": "Toolmaker", "vector": { "x": 0.78, "y": -0.65, "z": 0.82 } },
        { "id": 73, "keyword_zh": "修正", "keyword_en": "Fix", "archetype": "Toolmaker", "vector": { "x": 0.50, "y": -0.70, "z": 0.78 } },
        { "id": 74, "keyword_zh": "技能", "keyword_en": "Skill", "archetype": "Toolmaker", "vector": { "x": 0.45, "y": -0.55, "z": 0.86 } },
        { "id": 75, "keyword_zh": "獲利", "keyword_en": "Earn", "archetype": "Toolmaker", "vector": { "x": 0.92, "y": -0.40, "z": 0.72 } },
        { "id": 76, "keyword_zh": "累積", "keyword_en": "Stack", "archetype": "Toolmaker", "vector": { "x": 0.62, "y": -0.88, "z": 0.68 } },
        { "id": 77, "keyword_zh": "完工", "keyword_en": "Done", "archetype": "Toolmaker", "vector": { "x": 0.58, "y": -0.82, "z": 0.98 } },
        { "id": 78, "keyword_zh": "穩定", "keyword_en": "Firm", "archetype": "Toolmaker", "vector": { "x": 0.40, "y": -0.98, "z": 0.65 } },
        { "id": 79, "keyword_zh": "技藝", "keyword_en": "Craft", "archetype": "Toolmaker", "vector": { "x": 0.50, "y": -0.55, "z": 0.92 } },
        { "id": 80, "keyword_zh": "優化", "keyword_en": "Tune", "archetype": "Toolmaker", "vector": { "x": 0.65, "y": -0.65, "z": 0.85 } },
        { "id": 81, "keyword_zh": "分析", "keyword_en": "Scan", "archetype": "Sentry", "vector": { "x": 0.60, "y": -0.70, "z": -0.80 } },
        { "id": 82, "keyword_zh": "戰略", "keyword_en": "Plan", "archetype": "Sentry", "vector": { "x": 0.85, "y": -0.60, "z": -0.75 } },
        { "id": 83, "keyword_zh": "邏輯", "keyword_en": "Logic", "archetype": "Sentry", "vector": { "x": 0.70, "y": -0.95, "z": -0.90 } },
        { "id": 84, "keyword_zh": "架構", "keyword_en": "Frame", "archetype": "Sentry", "vector": { "x": 0.65, "y": -0.85, "z": -0.85 } },
        { "id": 85, "keyword_zh": "規劃", "keyword_en": "Map", "archetype": "Sentry", "vector": { "x": 0.75, "y": -0.80, "z": -0.60 } },
        { "id": 86, "keyword_zh": "佈局", "keyword_en": "Set", "archetype": "Sentry", "vector": { "x": 0.80, "y": -0.65, "z": -0.55 } },
        { "id": 87, "keyword_zh": "推理", "keyword_en": "Think", "archetype": "Sentry", "vector": { "x": 0.68, "y": -0.75, "z": -0.88 } },
        { "id": 88, "keyword_zh": "權威", "keyword_en": "Auth", "archetype": "Sentry", "vector": { "x": 0.90, "y": -0.50, "z": -0.40 } },
        { "id": 89, "keyword_zh": "專家", "keyword_en": "Pro", "archetype": "Sentry", "vector": { "x": 0.82, "y": -0.55, "z": -0.65 } },
        { "id": 90, "keyword_zh": "理論", "keyword_en": "Law", "archetype": "Sentry", "vector": { "x": 0.55, "y": -0.88, "z": -0.95 } },
        { "id": 91, "keyword_zh": "洞察", "keyword_en": "See", "archetype": "Sentry", "vector": { "x": 0.72, "y": -0.45, "z": -0.82 } },
        { "id": 92, "keyword_zh": "預測", "keyword_en": "Cast", "archetype": "Sentry", "vector": { "x": 0.78, "y": -0.40, "z": -0.92 } },
        { "id": 93, "keyword_zh": "智謀", "keyword_en": "Wits", "archetype": "Sentry", "vector": { "x": 0.88, "y": -0.58, "z": -0.70 } },
        { "id": 94, "keyword_zh": "原則", "keyword_en": "Rule", "archetype": "Sentry", "vector": { "x": 0.62, "y": -0.92, "z": -0.50 } },
        { "id": 95, "keyword_zh": "系統", "keyword_en": "Sys", "archetype": "Sentry", "vector": { "x": 0.58, "y": -0.98, "z": -0.78 } },
        { "id": 96, "keyword_zh": "驗證", "keyword_en": "Prove", "archetype": "Sentry", "vector": { "x": 0.50, "y": -0.90, "z": -0.68 } },
        { "id": 97, "keyword_zh": "守護", "keyword_en": "Guard", "archetype": "Helper", "vector": { "x": -0.90, "y": -0.85, "z": 0.90 } },
        { "id": 98, "keyword_zh": "服務", "keyword_en": "Serve", "archetype": "Helper", "vector": { "x": -0.95, "y": -0.60, "z": 0.85 } },
        { "id": 99, "keyword_zh": "協助", "keyword_en": "Help", "archetype": "Helper", "vector": { "x": -0.85, "y": -0.70, "z": 0.80 } },
        { "id": 100, "keyword_zh": "傳統", "keyword_en": "Old", "archetype": "Helper", "vector": { "x": -0.65, "y": -0.95, "z": 0.75 } },
        { "id": 101, "keyword_zh": "規範", "keyword_en": "Norm", "archetype": "Helper", "vector": { "x": -0.60, "y": -0.98, "z": 0.70 } },
        { "id": 102, "keyword_zh": "職責", "keyword_en": "Duty", "archetype": "Helper", "vector": { "x": -0.75, "y": -0.90, "z": 0.88 } },
        { "id": 103, "keyword_zh": "後勤", "keyword_en": "Rear", "archetype": "Helper", "vector": { "x": -0.55, "y": -0.80, "z": 0.95 } },
        { "id": 104, "keyword_zh": "維護", "keyword_en": "Keep", "archetype": "Helper", "vector": { "x": -0.50, "y": -0.88, "z": 0.92 } },
        { "id": 105, "keyword_zh": "安穩", "keyword_en": "Safe", "archetype": "Helper", "vector": { "x": -0.80, "y": -0.92, "z": 0.65 } },
        { "id": 106, "keyword_zh": "服從", "keyword_en": "Obey", "archetype": "Helper", "vector": { "x": -0.70, "y": -0.85, "z": 0.60 } },
        { "id": 107, "keyword_zh": "忠誠", "keyword_en": "Loyal", "archetype": "Helper", "vector": { "x": -0.92, "y": -0.75, "z": 0.55 } },
        { "id": 108, "keyword_zh": "照料", "keyword_en": "Care", "archetype": "Helper", "vector": { "x": -0.98, "y": -0.50, "z": 0.98 } },
        { "id": 109, "keyword_zh": "秩序", "keyword_en": "Order", "archetype": "Helper", "vector": { "x": -0.58, "y": -0.96, "z": 0.50 } },
        { "id": 110, "keyword_zh": "歸屬", "keyword_en": "Join", "archetype": "Helper", "vector": { "x": -0.88, "y": -0.55, "z": 0.45 } },
        { "id": 111, "keyword_zh": "信任", "keyword_en": "Trust", "archetype": "Helper", "vector": { "x": -0.82, "y": -0.65, "z": 0.40 } },
        { "id": 112, "keyword_zh": "承諾", "keyword_en": "Vow", "archetype": "Helper", "vector": { "x": -0.78, "y": -0.78, "z": 0.58 } },
        { "id": 113, "keyword_zh": "和平", "keyword_en": "Peace", "archetype": "Elder", "vector": { "x": -0.95, "y": -0.85, "z": -0.90 } },
        { "id": 114, "keyword_zh": "協調", "keyword_en": "Sync", "archetype": "Elder", "vector": { "x": -0.80, "y": -0.75, "z": -0.80 } },
        { "id": 115, "keyword_zh": "教育", "keyword_en": "Teach", "archetype": "Elder", "vector": { "x": -0.70, "y": -0.80, "z": -0.70 } },
        { "id": 116, "keyword_zh": "引導", "keyword_en": "Guide", "archetype": "Elder", "vector": { "x": -0.75, "y": -0.70, "z": -0.65 } },
        { "id": 117, "keyword_zh": "溝通", "keyword_en": "Talk", "archetype": "Elder", "vector": { "x": -0.90, "y": -0.60, "z": -0.75 } },
        { "id": 118, "keyword_zh": "文化", "keyword_en": "Cult", "archetype": "Elder", "vector": { "x": -0.60, "y": -0.90, "z": -0.95 } },
        { "id": 119, "keyword_zh": "傳承", "keyword_en": "Pass", "archetype": "Elder", "vector": { "x": -0.55, "y": -0.95, "z": -0.85 } },
        { "id": 120, "keyword_zh": "諮詢", "keyword_en": "Ask", "archetype": "Elder", "vector": { "x": -0.85, "y": -0.55, "z": -0.60 } },
        { "id": 121, "keyword_zh": "談判", "keyword_en": "Deal", "archetype": "Elder", "vector": { "x": -0.65, "y": -0.50, "z": -0.55 } },
        { "id": 122, "keyword_zh": "整合", "keyword_en": "Union", "archetype": "Elder", "vector": { "x": -0.72, "y": -0.88, "z": -0.50 } },
        { "id": 123, "keyword_zh": "智慧", "keyword_en": "Wise", "archetype": "Elder", "vector": { "x": -0.50, "y": -0.98, "z": -0.92 } },
        { "id": 124, "keyword_zh": "道德", "keyword_en": "Moral", "archetype": "Elder", "vector": { "x": -0.88, "y": -0.92, "z": -0.88 } },
        { "id": 125, "keyword_zh": "典範", "keyword_en": "Model", "archetype": "Elder", "vector": { "x": -0.68, "y": -0.94, "z": -0.82 } },
        { "id": 126, "keyword_zh": "導師", "keyword_en": "Guru", "archetype": "Elder", "vector": { "x": -0.82, "y": -0.68, "z": -0.98 } },
        { "id": 127, "keyword_zh": "組織", "keyword_en": "Group", "archetype": "Elder", "vector": { "x": -0.78, "y": -0.82, "z": -0.45 } },
        { "id": 128, "keyword_zh": "協議", "keyword_en": "Pact", "archetype": "Elder", "vector": { "x": -0.62, "y": -0.72, "z": -0.40 } }
    ]
}

export default {
    load() {
        return keywords
    }
}