const keywords = {
    "meta": {
        "model": "Neuro-Archetypes v4.0 (IRH Code System)",
        "version": "4.0",
        "total_keywords": 64,
        "axis_logic": {
            "x": "Drive ( I:Individual/Competition > 0 | O:Others/Connection < 0 )",
            "y": "Topology ( R:Real/Sensory > 0 | V:Virtual/Prediction < 0 )",
            "z": "Entropy ( H:Hot/Chaos > 0 | C:Cold/Order < 0 )"
        }
    },
    "keywords": [
        { "id": 1, "keyword_zh": "征服", "keyword_en": "Conquer", "archetype": "Hunter", "vector": { "x": 0.95, "y": 0.90, "z": 0.88 } },
        { "id": 2, "keyword_zh": "追趕", "keyword_en": "Chase", "archetype": "Hunter", "vector": { "x": 0.88, "y": 0.85, "z": 0.82 } },
        { "id": 3, "keyword_zh": "稱霸", "keyword_en": "Dominate", "archetype": "Hunter", "vector": { "x": 0.92, "y": 0.80, "z": 0.90 } },
        { "id": 4, "keyword_zh": "贏家", "keyword_en": "Winner", "archetype": "Hunter", "vector": { "x": 0.98, "y": 0.75, "z": 0.85 } },
        { "id": 5, "keyword_zh": "衝刺", "keyword_en": "Sprint", "archetype": "Hunter", "vector": { "x": 0.75, "y": 0.70, "z": 0.65 } },
        { "id": 6, "keyword_zh": "競爭", "keyword_en": "Compete", "archetype": "Hunter", "vector": { "x": 0.65, "y": 0.60, "z": 0.68 } },
        { "id": 7, "keyword_zh": "奪冠", "keyword_en": "Champ", "archetype": "Hunter", "vector": { "x": 0.70, "y": 0.55, "z": 0.72 } },
        { "id": 8, "keyword_zh": "戰鬥", "keyword_en": "Fight", "archetype": "Hunter", "vector": { "x": 0.60, "y": 0.65, "z": 0.58 } },
        { "id": 9, "keyword_zh": "野心", "keyword_en": "Ambition", "archetype": "Hunter", "vector": { "x": 0.55, "y": 0.50, "z": 0.60 } },
        { "id": 10, "keyword_zh": "冒險", "keyword_en": "Adventure", "archetype": "Hunter", "vector": { "x": 0.45, "y": 0.48, "z": 0.52 } },
        { "id": 11, "keyword_zh": "挑戰", "keyword_en": "Challenge", "archetype": "Hunter", "vector": { "x": 0.35, "y": 0.40, "z": 0.38 } },
        { "id": 12, "keyword_zh": "權力", "keyword_en": "Power", "archetype": "Hunter", "vector": { "x": 0.25, "y": 0.30, "z": 0.28 } },
        { "id": 13, "keyword_zh": "操控", "keyword_en": "Control", "archetype": "Hunter", "vector": { "x": 0.20, "y": 0.25, "z": 0.22 } },
        { "id": 14, "keyword_zh": "壯遊", "keyword_en": "GrandTour", "archetype": "Hunter", "vector": { "x": 0.15, "y": 0.18, "z": 0.20 } },
        { "id": 15, "keyword_zh": "實戰", "keyword_en": "Combat", "archetype": "Hunter", "vector": { "x": 0.30, "y": 0.15, "z": 0.35 } },
        { "id": 16, "keyword_zh": "衝擊", "keyword_en": "Impact", "archetype": "Hunter", "vector": { "x": 0.18, "y": 0.35, "z": 0.15 } },
        { "id": 17, "keyword_zh": "顛覆", "keyword_en": "Disrupt", "archetype": "Pioneer", "vector": { "x": 0.95, "y": 0.92, "z": -0.90 } },
        { "id": 18, "keyword_zh": "狂熱", "keyword_en": "Fanatic", "archetype": "Pioneer", "vector": { "x": 0.88, "y": 0.98, "z": -0.85 } },
        { "id": 19, "keyword_zh": "前衛", "keyword_en": "Avant", "archetype": "Pioneer", "vector": { "x": 0.85, "y": 0.85, "z": -0.80 } },
        { "id": 20, "keyword_zh": "原創", "keyword_en": "Original", "archetype": "Pioneer", "vector": { "x": 0.90, "y": 0.80, "z": -0.95 } },
        { "id": 21, "keyword_zh": "創新", "keyword_en": "Innovate", "archetype": "Pioneer", "vector": { "x": 0.75, "y": 0.70, "z": -0.65 } },
        { "id": 22, "keyword_zh": "變革", "keyword_en": "Reform", "archetype": "Pioneer", "vector": { "x": 0.65, "y": 0.75, "z": -0.60 } },
        { "id": 23, "keyword_zh": "願景", "keyword_en": "Vision", "archetype": "Pioneer", "vector": { "x": 0.70, "y": 0.60, "z": -0.72 } },
        { "id": 24, "keyword_zh": "靈感", "keyword_en": "Idea", "archetype": "Pioneer", "vector": { "x": 0.60, "y": 0.55, "z": -0.58 } },
        { "id": 25, "keyword_zh": "重塑", "keyword_en": "Reshape", "archetype": "Pioneer", "vector": { "x": 0.55, "y": 0.65, "z": -0.50 } },
        { "id": 26, "keyword_zh": "發明", "keyword_en": "Invent", "archetype": "Pioneer", "vector": { "x": 0.48, "y": 0.50, "z": -0.45 } },
        { "id": 27, "keyword_zh": "實驗", "keyword_en": "Lab", "archetype": "Pioneer", "vector": { "x": 0.35, "y": 0.40, "z": -0.30 } },
        { "id": 28, "keyword_zh": "新奇", "keyword_en": "Novel", "archetype": "Pioneer", "vector": { "x": 0.25, "y": 0.35, "z": -0.28 } },
        { "id": 29, "keyword_zh": "獨特", "keyword_en": "Unique", "archetype": "Pioneer", "vector": { "x": 0.30, "y": 0.25, "z": -0.35 } },
        { "id": 30, "keyword_zh": "探索", "keyword_en": "Explore", "archetype": "Pioneer", "vector": { "x": 0.20, "y": 0.30, "z": -0.20 } },
        { "id": 31, "keyword_zh": "幻想", "keyword_en": "Fantasy", "archetype": "Pioneer", "vector": { "x": 0.15, "y": 0.20, "z": -0.18 } },
        { "id": 32, "keyword_zh": "未來", "keyword_en": "Future", "archetype": "Pioneer", "vector": { "x": 0.18, "y": 0.15, "z": -0.25 } },
        { "id": 33, "keyword_zh": "狂歡", "keyword_en": "Revel", "archetype": "Gatherer", "vector": { "x": -0.90, "y": 0.95, "z": 0.88 } },
        { "id": 34, "keyword_zh": "閃耀", "keyword_en": "Shine", "archetype": "Gatherer", "vector": { "x": -0.95, "y": 0.85, "z": 0.80 } },
        { "id": 35, "keyword_zh": "熱鬧", "keyword_en": "Bustle", "archetype": "Gatherer", "vector": { "x": -0.85, "y": 0.92, "z": 0.75 } },
        { "id": 36, "keyword_zh": "聚會", "keyword_en": "Gather", "archetype": "Gatherer", "vector": { "x": -0.88, "y": 0.80, "z": 0.85 } },
        { "id": 37, "keyword_zh": "魅力", "keyword_en": "Charm", "archetype": "Gatherer", "vector": { "x": -0.75, "y": 0.70, "z": 0.72 } },
        { "id": 38, "keyword_zh": "熱情", "keyword_en": "Passion", "archetype": "Gatherer", "vector": { "x": -0.80, "y": 0.75, "z": 0.65 } },
        { "id": 39, "keyword_zh": "體驗", "keyword_en": "Feel", "archetype": "Gatherer", "vector": { "x": -0.65, "y": 0.60, "z": 0.78 } },
        { "id": 40, "keyword_zh": "驚喜", "keyword_en": "Surprise", "archetype": "Gatherer", "vector": { "x": -0.70, "y": 0.65, "z": 0.60 } },
        { "id": 41, "keyword_zh": "活潑", "keyword_en": "Lively", "archetype": "Gatherer", "vector": { "x": -0.55, "y": 0.50, "z": 0.58 } },
        { "id": 42, "keyword_zh": "互動", "keyword_en": "React", "archetype": "Gatherer", "vector": { "x": -0.60, "y": 0.55, "z": 0.52 } },
        { "id": 43, "keyword_zh": "玩樂", "keyword_en": "Play", "archetype": "Gatherer", "vector": { "x": -0.40, "y": 0.45, "z": 0.42 } },
        { "id": 44, "keyword_zh": "人氣", "keyword_en": "Popular", "archetype": "Gatherer", "vector": { "x": -0.35, "y": 0.38, "z": 0.35 } },
        { "id": 45, "keyword_zh": "暢談", "keyword_en": "Chat", "archetype": "Gatherer", "vector": { "x": -0.25, "y": 0.20, "z": 0.30 } },
        { "id": 46, "keyword_zh": "流行", "keyword_en": "Trend", "archetype": "Gatherer", "vector": { "x": -0.30, "y": 0.25, "z": 0.28 } },
        { "id": 47, "keyword_zh": "隨性", "keyword_en": "Casual", "archetype": "Gatherer", "vector": { "x": -0.15, "y": 0.15, "z": 0.20 } },
        { "id": 48, "keyword_zh": "結交", "keyword_en": "Social", "archetype": "Gatherer", "vector": { "x": -0.20, "y": 0.10, "z": 0.18 } },
        { "id": 49, "keyword_zh": "共鳴", "keyword_en": "Resonate", "archetype": "Shaman", "vector": { "x": -0.98, "y": 0.95, "z": -0.92 } },
        { "id": 50, "keyword_zh": "領悟", "keyword_en": "Realize", "archetype": "Shaman", "vector": { "x": -0.90, "y": 0.88, "z": -0.85 } },
        { "id": 51, "keyword_zh": "靈性", "keyword_en": "Spirit", "archetype": "Shaman", "vector": { "x": -0.85, "y": 0.90, "z": -0.95 } },
        { "id": 52, "keyword_zh": "奉獻", "keyword_en": "Devote", "archetype": "Shaman", "vector": { "x": -0.92, "y": 0.80, "z": -0.82 } },
        { "id": 53, "keyword_zh": "慈悲", "keyword_en": "Mercy", "archetype": "Shaman", "vector": { "x": -0.75, "y": 0.65, "z": -0.70 } },
        { "id": 54, "keyword_zh": "信仰", "keyword_en": "Faith", "archetype": "Shaman", "vector": { "x": -0.80, "y": 0.60, "z": -0.78 } },
        { "id": 55, "keyword_zh": "療癒", "keyword_en": "Heal", "archetype": "Shaman", "vector": { "x": -0.70, "y": 0.72, "z": -0.65 } },
        { "id": 56, "keyword_zh": "啟發", "keyword_en": "Inspire", "archetype": "Shaman", "vector": { "x": -0.65, "y": 0.55, "z": -0.75 } },
        { "id": 57, "keyword_zh": "直覺", "keyword_en": "Intuit", "archetype": "Shaman", "vector": { "x": -0.60, "y": 0.50, "z": -0.68 } },
        { "id": 58, "keyword_zh": "自由", "keyword_en": "Free", "archetype": "Shaman", "vector": { "x": -0.55, "y": 0.75, "z": -0.45 } },
        { "id": 59, "keyword_zh": "感應", "keyword_en": "Sense", "archetype": "Shaman", "vector": { "x": -0.40, "y": 0.40, "z": -0.35 } },
        { "id": 60, "keyword_zh": "相信", "keyword_en": "Believe", "archetype": "Shaman", "vector": { "x": -0.35, "y": 0.30, "z": -0.42 } },
        { "id": 61, "keyword_zh": "祈禱", "keyword_en": "Pray", "archetype": "Shaman", "vector": { "x": -0.30, "y": 0.25, "z": -0.38 } },
        { "id": 62, "keyword_zh": "緣分", "keyword_en": "Destiny", "archetype": "Shaman", "vector": { "x": -0.20, "y": 0.35, "z": -0.22 } },
        { "id": 63, "keyword_zh": "感動", "keyword_en": "Moved", "archetype": "Shaman", "vector": { "x": -0.25, "y": 0.20, "z": -0.28 } },
        { "id": 64, "keyword_zh": "沈浸", "keyword_en": "Immerse", "archetype": "Shaman", "vector": { "x": -0.15, "y": 0.45, "z": -0.18 } },
        { "id": 65, "keyword_zh": "精確", "keyword_en": "Precise", "archetype": "Toolmaker", "vector": { "x": 0.85, "y": -0.95, "z": 0.90 } },
        { "id": 66, "keyword_zh": "完工", "keyword_en": "Done", "archetype": "Toolmaker", "vector": { "x": 0.80, "y": -0.90, "z": 0.88 } },
        { "id": 67, "keyword_zh": "執行", "keyword_en": "Execute", "archetype": "Toolmaker", "vector": { "x": 0.92, "y": -0.85, "z": 0.82 } },
        { "id": 68, "keyword_zh": "實務", "keyword_en": "Practical", "archetype": "Toolmaker", "vector": { "x": 0.88, "y": -0.80, "z": 0.95 } },
        { "id": 69, "keyword_zh": "效率", "keyword_en": "Efficient", "archetype": "Toolmaker", "vector": { "x": 0.75, "y": -0.70, "z": 0.72 } },
        { "id": 70, "keyword_zh": "產出", "keyword_en": "Output", "archetype": "Toolmaker", "vector": { "x": 0.70, "y": -0.75, "z": 0.68 } },
        { "id": 71, "keyword_zh": "校準", "keyword_en": "Align", "archetype": "Toolmaker", "vector": { "x": 0.65, "y": -0.60, "z": 0.78 } },
        { "id": 72, "keyword_zh": "技藝", "keyword_en": "Craft", "archetype": "Toolmaker", "vector": { "x": 0.60, "y": -0.55, "z": 0.75 } },
        { "id": 73, "keyword_zh": "累積", "keyword_en": "Stack", "archetype": "Toolmaker", "vector": { "x": 0.55, "y": -0.65, "z": 0.62 } },
        { "id": 74, "keyword_zh": "精進", "keyword_en": "Mastery", "archetype": "Toolmaker", "vector": { "x": 0.50, "y": -0.50, "z": 0.80 } },
        { "id": 75, "keyword_zh": "實作", "keyword_en": "HandsOn", "archetype": "Toolmaker", "vector": { "x": 0.35, "y": -0.40, "z": 0.45 } },
        { "id": 76, "keyword_zh": "修繕", "keyword_en": "Fix", "archetype": "Toolmaker", "vector": { "x": 0.40, "y": -0.30, "z": 0.48 } },
        { "id": 77, "keyword_zh": "操練", "keyword_en": "Drill", "archetype": "Toolmaker", "vector": { "x": 0.30, "y": -0.25, "z": 0.38 } },
        { "id": 78, "keyword_zh": "優化", "keyword_en": "Optimize", "archetype": "Toolmaker", "vector": { "x": 0.25, "y": -0.35, "z": 0.32 } },
        { "id": 79, "keyword_zh": "建造", "keyword_en": "Build", "archetype": "Toolmaker", "vector": { "x": 0.20, "y": -0.20, "z": 0.42 } },
        { "id": 80, "keyword_zh": "自造", "keyword_en": "DIY", "archetype": "Toolmaker", "vector": { "x": 0.15, "y": -0.15, "z": 0.28 } },
        { "id": 81, "keyword_zh": "邏輯", "keyword_en": "Logic", "archetype": "Sentry", "vector": { "x": 0.90, "y": -0.95, "z": -0.90 } },
        { "id": 82, "keyword_zh": "嚴謹", "keyword_en": "Rigorous", "archetype": "Sentry", "vector": { "x": 0.95, "y": -0.92, "z": -0.85 } },
        { "id": 83, "keyword_zh": "原理", "keyword_en": "Theory", "archetype": "Sentry", "vector": { "x": 0.85, "y": -0.88, "z": -0.95 } },
        { "id": 84, "keyword_zh": "證明", "keyword_en": "Proof", "archetype": "Sentry", "vector": { "x": 0.88, "y": -0.85, "z": -0.82 } },
        { "id": 85, "keyword_zh": "戰略", "keyword_en": "Strategy", "archetype": "Sentry", "vector": { "x": 0.75, "y": -0.70, "z": -0.75 } },
        { "id": 86, "keyword_zh": "架構", "keyword_en": "Struct", "archetype": "Sentry", "vector": { "x": 0.70, "y": -0.75, "z": -0.65 } },
        { "id": 87, "keyword_zh": "分析", "keyword_en": "Analyze", "archetype": "Sentry", "vector": { "x": 0.65, "y": -0.60, "z": -0.80 } },
        { "id": 88, "keyword_zh": "預判", "keyword_en": "Predict", "archetype": "Sentry", "vector": { "x": 0.68, "y": -0.55, "z": -0.72 } },
        { "id": 89, "keyword_zh": "查核", "keyword_en": "Verify", "archetype": "Sentry", "vector": { "x": 0.60, "y": -0.65, "z": -0.50 } },
        { "id": 90, "keyword_zh": "演算", "keyword_en": "Compute", "archetype": "Sentry", "vector": { "x": 0.55, "y": -0.50, "z": -0.68 } },
        { "id": 91, "keyword_zh": "深思", "keyword_en": "Ponder", "archetype": "Sentry", "vector": { "x": 0.40, "y": -0.45, "z": -0.45 } },
        { "id": 92, "keyword_zh": "研究", "keyword_en": "Study", "archetype": "Sentry", "vector": { "x": 0.45, "y": -0.40, "z": -0.38 } },
        { "id": 93, "keyword_zh": "佈局", "keyword_en": "Setup", "archetype": "Sentry", "vector": { "x": 0.35, "y": -0.30, "z": -0.32 } },
        { "id": 94, "keyword_zh": "依據", "keyword_en": "Basis", "archetype": "Sentry", "vector": { "x": 0.30, "y": -0.25, "z": -0.40 } },
        { "id": 95, "keyword_zh": "洞見", "keyword_en": "Insight", "archetype": "Sentry", "vector": { "x": 0.20, "y": -0.20, "z": -0.28 } },
        { "id": 96, "keyword_zh": "確認", "keyword_en": "Confirm", "archetype": "Sentry", "vector": { "x": 0.15, "y": -0.15, "z": -0.22 } },
        { "id": 97, "keyword_zh": "盡責", "keyword_en": "Dutiful", "archetype": "Helper", "vector": { "x": -0.92, "y": -0.85, "z": 0.88 } },
        { "id": 98, "keyword_zh": "歸屬", "keyword_en": "Belong", "archetype": "Helper", "vector": { "x": -0.88, "y": -0.90, "z": 0.82 } },
        { "id": 99, "keyword_zh": "守護", "keyword_en": "Guard", "archetype": "Helper", "vector": { "x": -0.95, "y": -0.75, "z": 0.90 } },
        { "id": 100, "keyword_zh": "安定", "keyword_en": "Stable", "archetype": "Helper", "vector": { "x": -0.85, "y": -0.80, "z": 0.78 } },
        { "id": 101, "keyword_zh": "服務", "keyword_en": "Serve", "archetype": "Helper", "vector": { "x": -0.75, "y": -0.65, "z": 0.72 } },
        { "id": 102, "keyword_zh": "協助", "keyword_en": "Assist", "archetype": "Helper", "vector": { "x": -0.70, "y": -0.60, "z": 0.68 } },
        { "id": 103, "keyword_zh": "支援", "keyword_en": "Support", "archetype": "Helper", "vector": { "x": -0.65, "y": -0.70, "z": 0.85 } },
        { "id": 104, "keyword_zh": "安穩", "keyword_en": "Secure", "archetype": "Helper", "vector": { "x": -0.60, "y": -0.85, "z": 0.60 } },
        { "id": 105, "keyword_zh": "承諾", "keyword_en": "Promise", "archetype": "Helper", "vector": { "x": -0.55, "y": -0.50, "z": 0.55 } },
        { "id": 106, "keyword_zh": "誠信", "keyword_en": "Honest", "archetype": "Helper", "vector": { "x": -0.50, "y": -0.55, "z": 0.52 } },
        { "id": 107, "keyword_zh": "互助", "keyword_en": "Help", "archetype": "Helper", "vector": { "x": -0.40, "y": -0.40, "z": 0.45 } },
        { "id": 108, "keyword_zh": "傾聽", "keyword_en": "Listen", "archetype": "Helper", "vector": { "x": -0.35, "y": -0.45, "z": 0.40 } },
        { "id": 109, "keyword_zh": "收藏", "keyword_en": "Collect", "archetype": "Helper", "vector": { "x": -0.30, "y": -0.35, "z": 0.48 } },
        { "id": 110, "keyword_zh": "整潔", "keyword_en": "Tidy", "archetype": "Helper", "vector": { "x": -0.25, "y": -0.30, "z": 0.42 } },
        { "id": 111, "keyword_zh": "合作", "keyword_en": "Cooperate", "archetype": "Helper", "vector": { "x": -0.15, "y": -0.20, "z": 0.35 } },
        { "id": 112, "keyword_zh": "陪伴", "keyword_en": "Company", "archetype": "Helper", "vector": { "x": -0.20, "y": -0.15, "z": 0.38 } },
        { "id": 113, "keyword_zh": "和平", "keyword_en": "Peace", "archetype": "Elder", "vector": { "x": -0.95, "y": -0.90, "z": -0.92 } },
        { "id": 114, "keyword_zh": "智慧", "keyword_en": "Wisdom", "archetype": "Elder", "vector": { "x": -0.88, "y": -0.95, "z": -0.85 } },
        { "id": 115, "keyword_zh": "傳承", "keyword_en": "Legacy", "archetype": "Elder", "vector": { "x": -0.90, "y": -0.85, "z": -0.88 } },
        { "id": 116, "keyword_zh": "道德", "keyword_en": "Moral", "archetype": "Elder", "vector": { "x": -0.85, "y": -0.92, "z": -0.80 } },
        { "id": 117, "keyword_zh": "教誨", "keyword_en": "Teach", "archetype": "Elder", "vector": { "x": -0.75, "y": -0.70, "z": -0.72 } },
        { "id": 118, "keyword_zh": "共識", "keyword_en": "Consensus", "archetype": "Elder", "vector": { "x": -0.70, "y": -0.65, "z": -0.55 } },
        { "id": 119, "keyword_zh": "協調", "keyword_en": "Coord", "archetype": "Elder", "vector": { "x": -0.65, "y": -0.75, "z": -0.68 } },
        { "id": 120, "keyword_zh": "文化", "keyword_en": "Culture", "archetype": "Elder", "vector": { "x": -0.60, "y": -0.80, "z": -0.90 } },
        { "id": 121, "keyword_zh": "典範", "keyword_en": "Model", "archetype": "Elder", "vector": { "x": -0.55, "y": -0.85, "z": -0.75 } },
        { "id": 122, "keyword_zh": "交流", "keyword_en": "Exchange", "archetype": "Elder", "vector": { "x": -0.50, "y": -0.60, "z": -0.65 } },
        { "id": 123, "keyword_zh": "指引", "keyword_en": "Guide", "archetype": "Elder", "vector": { "x": -0.40, "y": -0.45, "z": -0.48 } },
        { "id": 124, "keyword_zh": "周全", "keyword_en": "Thorough", "archetype": "Elder", "vector": { "x": -0.35, "y": -0.40, "z": -0.35 } },
        { "id": 125, "keyword_zh": "關懷", "keyword_en": "Care", "archetype": "Elder", "vector": { "x": -0.30, "y": -0.35, "z": -0.40 } },
        { "id": 126, "keyword_zh": "包容", "keyword_en": "Inclusive", "archetype": "Elder", "vector": { "x": -0.25, "y": -0.30, "z": -0.28 } },
        { "id": 127, "keyword_zh": "尊重", "keyword_en": "Respect", "archetype": "Elder", "vector": { "x": -0.20, "y": -0.25, "z": -0.22 } },
        { "id": 128, "keyword_zh": "顧問", "keyword_en": "Consult", "archetype": "Elder", "vector": { "x": -0.15, "y": -0.20, "z": -0.30 } }
    ]
}

export default {
    load() {
        return keywords
    }
}